name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: # Specify your branches here
      - main # The 'main' branch
      - 'releases/*' # The release branches

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: comment-db
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run Tests and Generate Coverage Report
        run: mvn clean verify --file pom.xml -Dspring.datasource.url=${{ env.SPRING_DATASOURCE_URL }} -Dspring.datasource.username=${{ secrets.SPRING_DATASOURCE_USERNAME }} -Dspring.datasource.password=${{ secrets.SPRING_DATASOURCE_PASSWORD }}
      - name: Upload JaCoCo Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: JaCoCo Coverage Report
          path: target/site/jacoco/jacoco.xml

  qodana:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download JaCoCo Coverage Report
        uses: actions/download-artifact@v2
        with:
          name: JaCoCo Coverage Report
          path: target/site/jacoco/jacoco.xml
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.3
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          linter: "your-linter-type"  # Specify the linter, e.g., "java"
          additional-parameters: "--show-report -v /target/site/jacoco/jacoco.xml:/data/project/coverage-report"
